##Handling Categorical & Numerical Features Assignment

##Handling Categorical & Numerical Features Assignment

In [8]:
import pandas as pd
import sklearn
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [4]:

# Load the dataset
df = pd.read_csv('/content/credit_risk_dataset.csv')

# Display the first 5 rows of the DataFrame
display(df.head())

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [5]:
# Display basic information about the DataFrame
df.info()

# Display descriptive statistics for all columns, including categorical
display(df.describe(include='all'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  object
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  object
 5   loan_grade                  32581 non-null  object
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  object
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 3.0+ MB

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,32581,31686.000000,32581,32581,32581.000000,29465.000000,32581.000000,32581.000000,32581,32581.000000
unique,NaN,NaN,4,NaN,6,7,NaN,NaN,NaN,NaN,2,NaN
top,NaN,NaN,RENT,NaN,EDUCATION,A,NaN,NaN,NaN,NaN,N,NaN
freq,NaN,NaN,16446,NaN,6453,10777,NaN,NaN,NaN,NaN,26836,NaN
mean,27.734600,6.607485e+04,NaN,4.789686,NaN,NaN,9589.371106,11.011695,0.218164,0.170203,NaN,5.804211
std,6.348078,6.198312e+04,NaN,4.142630,NaN,NaN,6322.086646,3.240459,0.413006,0.106782,NaN,4.055001
min,20.000000,4.000000e+03,NaN,0.000000,NaN,NaN,500.000000,5.420000,0.000000,0.000000,NaN,2.000000
25%,23.000000,3.850000e+04,NaN,2.000000,NaN,NaN,5000.000000,7.900000,0.000000,0.090000,NaN,3.000000
50%,26.000000,5.500000e+04,NaN,4.000000,NaN,NaN,8000.000000,10.990000,0.000000,0.150000,NaN,4.000000
75%,30.000000,7.920000e+04,NaN,7.000000,NaN,NaN,12200.000000,13.470000,0.000000,0.230000,NaN,8.000000
max,144.000000,6.000000e+06,NaN,123.000000,NaN,NaN,35000.000000,23.220000,1.000000,0.830000,NaN,30.000000

## **Performing Encoding**

#### **Label Encoding**

In [26]:
le = LabelEncoder()
defile=le.fit_transform(df.person_home_ownership)
display(defile)

array([3, 2, 0, ..., 3, 0, 3])

In [29]:
#Replace the 'person_home_ownership' column in df with the encoded values
df['person_home_ownership'] = defile
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,3,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,2,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,0,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,3,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,3,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [ ]:
display(df.head())

In [30]:

# Identify categorical columns to encode
categorical_cols_encode = ['loan_intent', 'loan_grade']

# Create a OneHotEncoder instance
one_hot_encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Fit and transform the selected categorical columns
encoded_features = one_hot_encoder.fit_transform(df[categorical_cols_encode])

# Create a DataFrame from the encoded features with appropriate column names
encoded_feature_names = one_hot_encoder.get_feature_names_out(categorical_cols_encode)
df_encoded = pd.DataFrame(encoded_features, columns=encoded_feature_names, index=df.index)

# Concatenate the new encoded features with the original DataFrame
df = pd.concat([df, df_encoded], axis=1)

# Drop the original categorical columns that have been encoded
df = df.drop(columns=categorical_cols_encode)

# Display the first few rows of the updated DataFrame to show the encoded features
display(df.head())

,person_age,person_income,person_home_ownership,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,...,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,loan_grade_A,loan_grade_B,loan_grade_C,loan_grade_D,loan_grade_E,loan_grade_F,loan_grade_G
0,22,59000,3,123.0,35000,16.02,1,0.59,Y,3,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,21,9600,2,5.0,1000,11.14,0,0.10,N,2,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,25,9600,0,1.0,5500,12.87,1,0.57,N,3,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,23,65500,3,4.0,35000,15.23,1,0.53,N,2,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,24,54400,3,8.0,35000,14.27,1,0.55,Y,4,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [31]:
# Display the info of the updated DataFrame to see the new columns and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   person_age                     32581 non-null  int64
 1   person_income                  32581 non-null  int64
 2   person_home_ownership          32581 non-null  int64
 3   person_emp_length              31686 non-null  float64
 4   loan_amnt                      32581 non-null  int64
 5   loan_int_rate                  29465 non-null  float64
 6   loan_status                    32581 non-null  int64
 7   loan_percent_income            32581 non-null  float64
 8   cb_person_default_on_file      32581 non-null  object
 9   cb_person_cred_hist_length     32581 non-null  int64
 10  loan_intent_DEBTCONSOLIDATION  32581 non-null  float64
 11  loan_intent_EDUCATION          32581 non-null  float64
 12  loan_intent_HOMEIMPROVEMENT    32581 non-null  float64
 13  loan_intent_MEDICAL            32581 non-null  float64
 14  loan_intent_PERSONAL           32581 non-null  float64
 15  loan_intent_VENTURE            32581 non-null  float64
 16  loan_grade_A                   32581 non-null  float64
 17  loan_grade_B                   32581 non-null  float64
 18  loan_grade_C                   32581 non-null  float64
 19  loan_grade_D                   32581 non-null  float64
 20  loan_grade_E                   32581 non-null  float64
 21  loan_grade_F                   32581 non-null  float64
 22  loan_grade_G                   32581 non-null  float64
dtypes: float64(16), int64(6), object(1)
memory usage: 5.7+ MB

#### **Label Encoding for remaining categorical column**

In [32]:
le_default_on_file = LabelEncoder()
df['cb_person_default_on_file'] = le_default_on_file.fit_transform(df['cb_person_default_on_file'])
display(df.head())

,person_age,person_income,person_home_ownership,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,...,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,loan_grade_A,loan_grade_B,loan_grade_C,loan_grade_D,loan_grade_E,loan_grade_F,loan_grade_G
0,22,59000,3,123.0,35000,16.02,1,0.59,1,3,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,21,9600,2,5.0,1000,11.14,0,0.10,0,2,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,25,9600,0,1.0,5500,12.87,1,0.57,0,3,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,23,65500,3,4.0,35000,15.23,1,0.53,0,2,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,24,54400,3,8.0,35000,14.27,1,0.55,1,4,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

#### **Handling Missing Values and Scaling Numerical Features**

In [33]:
from sklearn.preprocessing import StandardScaler

# Identify numerical columns for scaling
numerical_cols = [
    'person_age',
    'person_income',
    'person_emp_length',
    'loan_amnt',
    'loan_int_rate',
    'loan_percent_income',
    'cb_person_cred_hist_length'
]

# Impute missing values with the mean for selected numerical columns
for col in ['person_emp_length', 'loan_int_rate']:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mean())

# Initialize StandardScaler
scaler = StandardScaler()

# Apply StandardScaler to the numerical columns
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

display(df.head())
df.info()

,person_age,person_income,person_home_ownership,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,...,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,loan_grade_A,loan_grade_B,loan_grade_C,loan_grade_D,loan_grade_E,loan_grade_F,loan_grade_G
0,-0.903374,-0.114143,3,28.935738,4.019404,1.625251,1,3.931411,1,-0.691554,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,-1.060904,-0.911147,2,0.051481,-1.358650,0.041636,0,-0.657458,0,-0.938167,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,-0.430783,-0.911147,0,-0.927646,-0.646849,0.603041,1,3.744110,0,-0.691554,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,-0.745843,-0.009274,3,-0.193301,4.019404,1.368887,1,3.369508,0,-0.938167,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,-0.588313,-0.188358,3,0.785826,4.019404,1.057357,1,3.556809,1,-0.444942,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   person_age                     32581 non-null  float64
 1   person_income                  32581 non-null  float64
 2   person_home_ownership          32581 non-null  int64
 3   person_emp_length              32581 non-null  float64
 4   loan_amnt                      32581 non-null  float64
 5   loan_int_rate                  32581 non-null  float64
 6   loan_status                    32581 non-null  int64
 7   loan_percent_income            32581 non-null  float64
 8   cb_person_default_on_file      32581 non-null  int64
 9   cb_person_cred_hist_length     32581 non-null  float64
 10  loan_intent_DEBTCONSOLIDATION  32581 non-null  float64
 11  loan_intent_EDUCATION          32581 non-null  float64
 12  loan_intent_HOMEIMPROVEMENT    32581 non-null  float64
 13  loan_intent_MEDICAL            32581 non-null  float64
 14  loan_intent_PERSONAL           32581 non-null  float64
 15  loan_intent_VENTURE            32581 non-null  float64
 16  loan_grade_A                   32581 non-null  float64
 17  loan_grade_B                   32581 non-null  float64
 18  loan_grade_C                   32581 non-null  float64
 19  loan_grade_D                   32581 non-null  float64
 20  loan_grade_E                   32581 non-null  float64
 21  loan_grade_F                   32581 non-null  float64
 22  loan_grade_G                   32581 non-null  float64
dtypes: float64(20), int64(3)
memory usage: 5.7 MB